### ISSUE TITLE
"ota sign" not available

### ISSUE THREAD

**Issue by xanathon** [digital-dream-labs/vector-web-setup#12]
In the readme:

"4. Sign the file after you've verified it's good: vector-web-setup ota-sign"

raises error: unknown command 'ota-sign'. See 'vector-web-setup --help'

"vector-web-setup --help" shows no command called "ota-sign", see screenshot

![image](https://user-images.githubusercontent.com/24546760/89101987-57bab400-d405-11ea-9d93-0976b0d36c7f.png)

**Comment by anant-kaushik** [comment]
You are right it should be `ota-approve`. I have made the necessary change.

**Comment by grant-olson** [comment]
This was a documentation error and the README has been updated.
