### ISSUE TITLE
Docker image contribution? 

### ISSUE THREAD

**Issue by xinity** [digital-dream-labs/vector-web-setup#9]
Hello,

Thanks a million for releasing vector-web-setup app.

As advised in the newsletter today I'm opening an issue. 

As this is a nodejs application I wanted to put my Docker knowledge in good use and wanted to ask if you would fancy a Docker image contribution for the vector-web-setup?

Let me know what you think,

Keep up this awesome work,
:+1:

**Comment by grant-olson** [comment]
We want to keep one set of instuctions and not:

1. Overload users with different ways to get the software up and running.
1. Install systems tools like Docker, which is great but a little complicated for many users.

However if you get a working app on Docker Hub and get some documentation that we can refer to we'll be happy to test it out and include a link and credit in our main README if it's a simple solution.

**Comment by xanathon** [comment]
I think you will have two kinds of users on this.

1. "normal" users that just want their Vector to run and will use the application as an alternbative for the phone app. For those this needs to be as simple as possible. installing node.js and packages for it will overwhelm them, so this will need to be simplified.
2. powerusers that want to use this in the future for Escape Pod and/or testing OSKR custom firmware builds

So it may be good idea if one could switch the application between a "user" and "advanced" mode. "User" mode would be quite simplified regarding (error) messages and UI/UX. "Advanced" or "dev" mode gives way more options and error messages/logs.

That way the "normal" users will not be overwhelmed and the dev users get the tools and informations they need. In addition, this is a tried and tested approach with other applications.
